import React, { createContext, useContext, useState, useEffect } from 'react';

// Simple language context for PL / EN
const LanguageContext = createContext({
  lang: 'pl',
  setLang: () => {},
  t: (key) => key,
});

const translations = {
  pl: {
    // General
    'lang.polish': 'Polski',
    'lang.english': 'Angielski',

    // Auth
    'auth.subtitle': 'System zarządzania wydrukami FDM',
    'auth.login': 'Logowanie',
    'auth.register': 'Rejestracja',
    'auth.name': 'Imię:',
    'auth.name.placeholder': 'Twoje imię',
    'auth.email': 'E-mail:',
    'auth.email.placeholder': 'twoj@email.pl',
    'auth.password': 'Hasło:',
    'auth.password.placeholder': 'Min. 6 znaków',
    'auth.login.submit': 'Zaloguj się',
    'auth.register.submit': 'Zarejestruj się',
    'auth.loading': 'Ładowanie...',
    'auth.error.passwordShort': 'Hasło musi mieć min. 6 znaków',
    'auth.error.generic': 'Wystąpił błąd. Spróbuj ponownie.',

    // Home
    'home.title': 'PrintLabApp',
    'home.subtitle': 'System zarządzania wydrukami FDM',
    'home.welcome': 'Witaj',
    'home.printsList': 'Lista wydruków',
    'home.printsList.desc': 'Zarządzaj swoimi modelami 3D',
    'home.filamentsList': 'Lista filamentów',
    'home.filamentsList.desc': 'Zarządzaj filamentami',
    'home.logout': 'Wyloguj się',
    'home.logout.desc': 'Zakończ sesję',
    'home.version': 'Wersja 1.0.0',

    // Navigation / common
    'common.back': '← Powrót',

    // Prints list
    'prints.title': 'Lista wydruków',
    'prints.add': '+ Dodaj model',
    'prints.found': 'Znaleziono',
    'prints.of': 'Wszystkich',
    'prints.models': 'modeli',
    'prints.loading': 'Ładowanie...',

    'prints.pricingSettings': 'Ustawienia cenowe',
    'prints.electricityPrice': 'Cena prądu (1 kWh):',
    'prints.packagingCost': 'Koszt pakowania:',
    'prints.shipping.mini': 'Koszt wysyłki (mini):',
    'prints.shipping.small': 'Koszt wysyłki (mała):',
    'prints.shipping.medium': 'Koszt wysyłki (średnia):',
    'prints.shipping.big': 'Koszt wysyłki (big):',

    'prints.inventory.filtered': 'Wartość magazynu (filtrowane):',
    'prints.inventory.all': 'Wartość całego magazynu:',
    'prints.inventory.items': 'Przedmioty (filament + prąd):',
    'prints.inventory.shippack': 'Wysyłka + pakowanie:',
    'prints.inventory.total': 'RAZEM:',

    // Prints filters
    'prints.filters.title': 'Filtry',
    'prints.filters.clear': 'Wyczyść',
    'prints.filters.printType': 'Typ druku:',
    'prints.filters.vaseMode': 'Tryb wazy',
    'prints.filters.fuzzyMode': 'Tryb fuzzy skin',
    'prints.filters.filamentType': 'Typ filamentu:',
    'prints.filters.all': 'Wszystkie',
    'prints.filters.category': 'Kategoria:',
    'prints.filters.sortBy': 'Sortuj według:',
    'prints.filters.sortBy.name': 'Nazwa',
    'prints.filters.sortBy.quantity': 'Ilość',
    'prints.filters.sortBy.printTime': 'Czas druku',
    'prints.filters.sortBy.price': 'Cena',
    'prints.filters.sortBy.category': 'Kategoria',
    'prints.filters.sortBy.filamentType': 'Typ filamentu',
    'prints.filters.sortBy.createdAt': 'Data dodania',
    'prints.filters.order': 'Kolejność:',
    'prints.filters.order.asc': 'Rosnąco',
    'prints.filters.order.desc': 'Malejąco',

    // Filaments list
    'filaments.title': 'Lista filamentów',
    'filaments.add': '+ Dodaj filament',
    'filaments.found': 'Znaleziono:',
    'filaments.all': 'Wszystkich:',
    'filaments.items': 'filamentów',
    'filaments.loading': 'Ładowanie...',

    // Filaments filters
    'filaments.filters.title': 'Filtry',
    'filaments.filters.clear': 'Wyczyść filtry',
    'filaments.filters.type': 'Typ filamentu',
    'filaments.filters.type.all': 'Wszystkie typy',
    'filaments.filters.producer': 'Producent',
    'filaments.filters.producer.all': 'Wszyscy producenci',
    'filaments.filters.color': 'Kolor',
    'filaments.filters.color.all': 'Wszystkie kolory',
    'filaments.filters.sort': 'Sortowanie',
    'filaments.filters.sortBy.type': 'Typ',
    'filaments.filters.sortBy.prod': 'Producent',
    'filaments.filters.sortBy.price': 'Cena',
    'filaments.filters.sortBy.createdAt': 'Data dodania',
    'filaments.filters.order.asc': 'Rosnąco',
    'filaments.filters.order.desc': 'Malejąco',

    // Print card
    'printcard.variants': 'Warianty:',
    'printcard.printTime': 'Czas druku:',
    'printcard.pricePerUnit': 'Cena (1 szt.):',
    'printcard.printMode': 'Tryb druku:',
    'printcard.category': 'Kategoria:',
    'printcard.size': 'Rozmiar:',
    'printcard.supports.on': 'SUPPORTS ON',
    'printcard.supports.off': 'SUPPORTS OFF',
    'printcard.vaseTag': 'WAZA',
    'printcard.fuzzyTag': 'FUZZY SKIN',

    'printcard.vaseLabel': 'Waza',
    'printcard.vaseWalls': 'ściany',
    'printcard.vaseBaseLayers': 'warstwy bazowe',
    'printcard.infillLabel': 'wypełnienie',
    'printcard.actions.edit': 'Edytuj',
    'printcard.actions.delete': 'Usuń',
    'printcard.actions.calc': 'Kalkulator',

    'printcard.calc.title': 'Kalkulator ceny',
    'printcard.calc.receipt': 'Paragon kalkulacji ceny',
    'printcard.calc.packageSize': 'Rozmiar paczki:',
    'printcard.calc.baseCosts': 'Koszty podstawowe:',
    'printcard.calc.material': 'Materiał',
    'printcard.calc.energy': 'Prąd',
    'printcard.calc.packaging': 'Pakowanie:',
    'printcard.calc.subtotal': 'Subtotal:',
    'printcard.calc.extraCosts': 'Dodatkowe koszty:',
    'printcard.calc.shipping': 'Wysyłka',
    'printcard.calc.totalCost': 'Koszt całkowity:',
    'printcard.calc.marginAndFinal': 'Marża i cena końcowa:',
    'printcard.calc.modelMargin': 'Marża modelu:',
    'printcard.calc.finalPrice': 'Cena sprzedaży (z marżą):',
    'printcard.calc.preview': 'Kalkulacja poglądowa:',
    'printcard.calc.targetPrice': 'Cena docelowa (testowa):',
    'printcard.calc.enterPrice': 'Wprowadź cenę',
    'printcard.calc.marginAtPrice': 'Marża przy tej cenie:',
    'printcard.calc.profitPerUnit': 'Zysk z jednej sztuki (z marżą):',
    'printcard.calc.profitInventory': 'Zysk z całego magazynu:',

    // Filament card
    'filamentcard.producer': 'Producent:',
    'filamentcard.pricePerKg': 'Cena za kg:',
    'filamentcard.colors': 'Kolory:',
    'filamentcard.noColors': 'Brak kolorów',
    'filamentcard.addedAt': 'Dodano:',
    'filamentcard.updatedAt': 'Zaktualizowano:',
    'filamentcard.specs.title': 'Parametry techniczne',
    'filamentcard.specs.diameter': 'Średnica:',
    'filamentcard.specs.diameterTolerance': 'Tolerancja:',
    'filamentcard.specs.finish': 'Powierzchnia:',
    'filamentcard.specs.density': 'Gęstość:',
    'filamentcard.specs.heatResistance': 'Odporność term.:',
    'filamentcard.specs.shoreHardness': 'Twardość Shore\'a:',
    'filamentcard.specs.impactStrength': 'Udarność:',
    'filamentcard.specs.youngsModulus': 'Moduł Younga:',
    'filamentcard.specs.retraction': 'Retrakcja:',
    'filamentcard.specs.nozzleDiameterMin': 'Min. śr. dyszy:',
    'filamentcard.specs.printSpeed': 'Prędkość druku:',

    // Add print modal
    'addprint.title': 'Dodaj nowy model',
    'addprint.tab.general': 'Ogólne',
    'addprint.tab.filament': 'Filament',
    'addprint.tab.print': 'Wydruk',
    'addprint.tab.pricing': 'Wycena',
    'addprint.name': 'Nazwa modelu:',
    'addprint.category': 'Kategoria:',
    'addprint.filamentVariants': 'Warianty filamentu',
    'addprint.variant': 'Wariant',
    'addprint.deleteVariant': 'Usuń wariant',
    'addprint.producer': 'Producent:',
    'addprint.chooseProducer': 'Wybierz producenta',
    'addprint.type': 'Typ filamentu:',
    'addprint.chooseType': 'Wybierz typ',
    'addprint.colorQuantityVariants': 'Warianty koloru i ilości:',
    'addprint.chooseColor': 'Wybierz kolor',
    'addprint.removeColorVariant': 'Usuń wariant koloru',
    'addprint.addColor': '+ Dodaj kolor',
    'addprint.addFilamentVariant': '+ Dodaj wariant filamentu',
    'addprint.printTimeSection': 'Czas druku',
    'addprint.printTimeHours': 'Czas druku (godziny):',
    'addprint.printTimeMinutes': 'Czas druku (minuty):',
    'addprint.weightSection': 'Waga wydruku',
    'addprint.weight': 'Waga (g):',
    'addprint.pricingSection': 'Ustawienia cenowe',
    'addprint.margin': 'Marża (%):',
    'addprint.packageSize': 'Rozmiar paczki:',
    'addprint.packageSize.mini': 'Mini',
    'addprint.packageSize.small': 'Mała',
    'addprint.packageSize.medium': 'Średnia',
    'addprint.packageSize.big': 'Big',
    'addprint.supportsSection': 'Podpory (Supports)',
    'addprint.supportsEnable': 'Włącz podpory',
    'addprint.supportsType': 'Typ podpór:',
    'addprint.supportsAngle': 'Kąt podpór (°):',
    'addprint.infillSection': 'Ustawienia wypełnienia',
    'addprint.vaseMode': 'Tryb wazy (Vase Mode)',
    'addprint.fuzzyMode': 'Fuzzy Skin',
    'addprint.vaseWalls': 'Liczba ścian:',
    'addprint.vaseBaseLayers': 'Warstwy bazowe:',
    'addprint.vaseSizeCorrection': 'Korekta rozmiaru wazy (cm):',
    'addprint.infillRate': 'Wypełnienie (%):',
    'addprint.infillType': 'Typ wypełnienia:',
    'common.cancel': 'Anuluj',
    'addprint.submit': 'Dodaj model',

    // Edit print modal
    'editprint.title': 'Edytuj wydruk:',
    'editprint.submit': 'Zapisz zmiany',

    // Add filament modal
    'addfilament.title': 'Dodaj nowy filament',
    'addfilament.type': 'Typ filamentu:',
    'addfilament.type.placeholder': 'np. PLA, PETG, ABS',
    'addfilament.producer': 'Producent:',
    'addfilament.producer.placeholder': 'np. Creality, Sunlu',
    'addfilament.pricePerKg': 'Cena za kilogram (zł):',
    'addfilament.pricePerKg.placeholder': '0.00',
    'addfilament.colors': 'Dostępne kolory:',
    'addfilament.colors.placeholder': 'Wpisz kolor i naciśnij Enter',
    'addfilament.addColor': '+ Dodaj',
    'addfilament.noColors': 'Brak dodanych kolorów',
    'addfilament.alert.noColor': 'Dodaj przynajmniej jeden kolor!',
    'addfilament.submit': 'Dodaj filament',
    'addfilament.specs.title': 'Parametry techniczne (opcjonalne)',
    'addfilament.specs.diameter': 'Średnica filamentu (mm):',
    'addfilament.specs.diameterTolerance': 'Tolerancja wymiarowa (mm):',
    'addfilament.specs.finish': 'Powierzchnia materiału:',
    'addfilament.specs.finish.placeholder': 'np. Połysk, Mat, Satyna',
    'addfilament.specs.density': 'Gęstość (g/cm³):',
    'addfilament.specs.heatResistance': 'Odporność termiczna (°C):',
    'addfilament.specs.shoreHardness': 'Twardość Shore\'a:',
    'addfilament.specs.impactStrength': 'Udarność karbu V (J/cm²):',
    'addfilament.specs.youngsModulus': 'Moduł Younga (MPa):',
    'addfilament.specs.retraction': 'Retrakcja (mm):',
    'addfilament.specs.nozzleDiameterMin': 'Min. średnica dyszy (mm):',
    'addfilament.specs.printSpeedMin': 'Prędkość druku min (mm/s):',
    'addfilament.specs.printSpeedMax': 'Prędkość druku max (mm/s):',

    // Edit filament modal
    'editfilament.title': 'Edytuj filament:',
    'editfilament.alert.noColor': 'Filament musi mieć przynajmniej jeden kolor!',
    'editfilament.submit': 'Zapisz zmiany',
  },
  en: {
    // General
    'lang.polish': 'Polish',
    'lang.english': 'English',

    // Auth
    'auth.subtitle': 'FDM print management system',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.name': 'Name:',
    'auth.name.placeholder': 'Your name',
    'auth.email': 'E-mail:',
    'auth.email.placeholder': 'your@email.com',
    'auth.password': 'Password:',
    'auth.password.placeholder': 'Min. 6 characters',
    'auth.login.submit': 'Sign in',
    'auth.register.submit': 'Sign up',
    'auth.loading': 'Loading...',
    'auth.error.passwordShort': 'Password must be at least 6 characters',
    'auth.error.generic': 'An error occurred. Please try again.',

    // Home
    'home.title': 'PrintLabApp',
    'home.subtitle': 'FDM print management system',
    'home.welcome': 'Welcome',
    'home.printsList': 'Prints list',
    'home.printsList.desc': 'Manage your 3D models',
    'home.filamentsList': 'Filaments list',
    'home.filamentsList.desc': 'Manage filaments',
    'home.logout': 'Logout',
    'home.logout.desc': 'End session',
    'home.version': 'Version 1.0.0',

    // Navigation / common
    'common.back': '← Back',

    // Prints list
    'prints.title': 'Prints list',
    'prints.add': '+ Add model',
    'prints.found': 'Found',
    'prints.of': 'All',
    'prints.models': 'models',
    'prints.loading': 'Loading...',

    'prints.pricingSettings': 'Pricing settings',
    'prints.electricityPrice': 'Electricity price (1 kWh):',
    'prints.packagingCost': 'Packaging cost:',
    'prints.shipping.mini': 'Shipping cost (mini):',
    'prints.shipping.small': 'Shipping cost (small):',
    'prints.shipping.medium': 'Shipping cost (medium):',
    'prints.shipping.big': 'Shipping cost (big):',

    'prints.inventory.filtered': 'Inventory value (filtered):',
    'prints.inventory.all': 'Total inventory value:',
    'prints.inventory.items': 'Items (filament + power):',
    'prints.inventory.shippack': 'Shipping + packaging:',
    'prints.inventory.total': 'TOTAL:',

    // Prints filters
    'prints.filters.title': 'Filters',
    'prints.filters.clear': 'Clear',
    'prints.filters.printType': 'Print type:',
    'prints.filters.vaseMode': 'Vase mode',
    'prints.filters.fuzzyMode': 'Fuzzy skin mode',
    'prints.filters.filamentType': 'Filament type:',
    'prints.filters.all': 'All',
    'prints.filters.category': 'Category:',
    'prints.filters.sortBy': 'Sort by:',
    'prints.filters.sortBy.name': 'Name',
    'prints.filters.sortBy.quantity': 'Quantity',
    'prints.filters.sortBy.printTime': 'Print time',
    'prints.filters.sortBy.price': 'Price',
    'prints.filters.sortBy.category': 'Category',
    'prints.filters.sortBy.filamentType': 'Filament type',
    'prints.filters.sortBy.createdAt': 'Created at',
    'prints.filters.order': 'Order:',
    'prints.filters.order.asc': 'Ascending',
    'prints.filters.order.desc': 'Descending',

    // Filaments list
    'filaments.title': 'Filaments list',
    'filaments.add': '+ Add filament',
    'filaments.found': 'Found:',
    'filaments.all': 'All:',
    'filaments.items': 'filaments',
    'filaments.loading': 'Loading...',

    // Filaments filters
    'filaments.filters.title': 'Filters',
    'filaments.filters.clear': 'Clear filters',
    'filaments.filters.type': 'Filament type',
    'filaments.filters.type.all': 'All types',
    'filaments.filters.producer': 'Producer',
    'filaments.filters.producer.all': 'All producers',
    'filaments.filters.color': 'Color',
    'filaments.filters.color.all': 'All colors',
    'filaments.filters.sort': 'Sorting',
    'filaments.filters.sortBy.type': 'Type',
    'filaments.filters.sortBy.prod': 'Producer',
    'filaments.filters.sortBy.price': 'Price',
    'filaments.filters.sortBy.createdAt': 'Created at',
    'filaments.filters.order.asc': 'Ascending',
    'filaments.filters.order.desc': 'Descending',

    // Print card
    'printcard.variants': 'Variants:',
    'printcard.printTime': 'Print time:',
    'printcard.pricePerUnit': 'Price (1 pc):',
    'printcard.printMode': 'Print mode:',
    'printcard.category': 'Category:',
    'printcard.size': 'Size:',
    'printcard.supports.on': 'SUPPORTS ON',
    'printcard.supports.off': 'SUPPORTS OFF',
    'printcard.vaseTag': 'VASE',
    'printcard.fuzzyTag': 'FUZZY SKIN',

    'printcard.vaseLabel': 'Vase',
    'printcard.vaseWalls': 'walls',
    'printcard.vaseBaseLayers': 'base layers',
    'printcard.infillLabel': 'infill',
    'printcard.actions.edit': 'Edit',
    'printcard.actions.delete': 'Delete',
    'printcard.actions.calc': 'Calculator',

    'printcard.calc.title': 'Price calculator',
    'printcard.calc.receipt': 'Price calculation receipt',
    'printcard.calc.packageSize': 'Package size:',
    'printcard.calc.baseCosts': 'Base costs:',
    'printcard.calc.material': 'Material',
    'printcard.calc.energy': 'Energy',
    'printcard.calc.packaging': 'Packaging:',
    'printcard.calc.subtotal': 'Subtotal:',
    'printcard.calc.extraCosts': 'Additional costs:',
    'printcard.calc.shipping': 'Shipping',
    'printcard.calc.totalCost': 'Total cost:',
    'printcard.calc.marginAndFinal': 'Margin and final price:',
    'printcard.calc.modelMargin': 'Model margin:',
    'printcard.calc.finalPrice': 'Sale price (with margin):',
    'printcard.calc.preview': 'What-if calculation:',
    'printcard.calc.targetPrice': 'Target price (test):',
    'printcard.calc.enterPrice': 'Enter price',
    'printcard.calc.marginAtPrice': 'Margin at this price:',
    'printcard.calc.profitPerUnit': 'Profit per unit (with margin):',
    'printcard.calc.profitInventory': 'Profit for full stock:',

    // Filament card
    'filamentcard.producer': 'Producer:',
    'filamentcard.pricePerKg': 'Price per kg:',
    'filamentcard.colors': 'Colors:',
    'filamentcard.noColors': 'No colors',
    'filamentcard.addedAt': 'Added:',
    'filamentcard.updatedAt': 'Updated:',
    'filamentcard.specs.title': 'Technical specifications',
    'filamentcard.specs.diameter': 'Diameter:',
    'filamentcard.specs.diameterTolerance': 'Tolerance:',
    'filamentcard.specs.finish': 'Surface finish:',
    'filamentcard.specs.density': 'Density:',
    'filamentcard.specs.heatResistance': 'Heat resist.:',
    'filamentcard.specs.shoreHardness': 'Shore hardness:',
    'filamentcard.specs.impactStrength': 'Impact strength:',
    'filamentcard.specs.youngsModulus': 'Young\'s modulus:',
    'filamentcard.specs.retraction': 'Retraction:',
    'filamentcard.specs.nozzleDiameterMin': 'Min. nozzle dia.:',
    'filamentcard.specs.printSpeed': 'Print speed:',

    // Add print modal
    'addprint.title': 'Add new model',
    'addprint.tab.general': 'General',
    'addprint.tab.filament': 'Filament',
    'addprint.tab.print': 'Print',
    'addprint.tab.pricing': 'Pricing',
    'addprint.name': 'Model name:',
    'addprint.category': 'Category:',
    'addprint.filamentVariants': 'Filament variants',
    'addprint.variant': 'Variant',
    'addprint.deleteVariant': 'Remove variant',
    'addprint.producer': 'Producer:',
    'addprint.chooseProducer': 'Choose producer',
    'addprint.type': 'Filament type:',
    'addprint.chooseType': 'Choose type',
    'addprint.colorQuantityVariants': 'Color & quantity variants:',
    'addprint.chooseColor': 'Choose color',
    'addprint.removeColorVariant': 'Remove color variant',
    'addprint.addColor': '+ Add color',
    'addprint.addFilamentVariant': '+ Add filament variant',
    'addprint.printTimeSection': 'Print time',
    'addprint.printTimeHours': 'Print time (hours):',
    'addprint.printTimeMinutes': 'Print time (minutes):',
    'addprint.weightSection': 'Print weight',
    'addprint.weight': 'Weight (g):',
    'addprint.pricingSection': 'Pricing settings',
    'addprint.margin': 'Margin (%):',
    'addprint.packageSize': 'Package size:',
    'addprint.packageSize.mini': 'Mini',
    'addprint.packageSize.small': 'Small',
    'addprint.packageSize.medium': 'Medium',
    'addprint.packageSize.big': 'Big',
    'addprint.supportsSection': 'Supports',
    'addprint.supportsEnable': 'Enable supports',
    'addprint.supportsType': 'Supports type:',
    'addprint.supportsAngle': 'Supports angle (°):',
    'addprint.infillSection': 'Infill settings',
    'addprint.vaseMode': 'Vase mode',
    'addprint.fuzzyMode': 'Fuzzy skin',
    'addprint.vaseWalls': 'Walls count:',
    'addprint.vaseBaseLayers': 'Base layers:',
    'addprint.vaseSizeCorrection': 'Vase size correction (cm):',
    'addprint.infillRate': 'Infill (%):',
    'addprint.infillType': 'Infill type:',
    'common.cancel': 'Cancel',
    'addprint.submit': 'Add model',

    // Edit print modal
    'editprint.title': 'Edit print:',
    'editprint.submit': 'Save changes',

    // Add filament modal
    'addfilament.title': 'Add new filament',
    'addfilament.type': 'Filament type:',
    'addfilament.type.placeholder': 'e.g. PLA, PETG, ABS',
    'addfilament.producer': 'Producer:',
    'addfilament.producer.placeholder': 'e.g. Creality, Sunlu',
    'addfilament.pricePerKg': 'Price per kilogram (PLN):',
    'addfilament.pricePerKg.placeholder': '0.00',
    'addfilament.colors': 'Available colors:',
    'addfilament.colors.placeholder': 'Type a color and press Enter',
    'addfilament.addColor': '+ Add',
    'addfilament.noColors': 'No colors added',
    'addfilament.alert.noColor': 'Add at least one color!',
    'addfilament.submit': 'Add filament',
    'addfilament.specs.title': 'Technical specifications (optional)',
    'addfilament.specs.diameter': 'Filament diameter (mm):',
    'addfilament.specs.diameterTolerance': 'Dimensional tolerance (mm):',
    'addfilament.specs.finish': 'Surface finish:',
    'addfilament.specs.finish.placeholder': 'e.g. Glossy, Matte, Satin',
    'addfilament.specs.density': 'Density (g/cm³):',
    'addfilament.specs.heatResistance': 'Heat resistance (°C):',
    'addfilament.specs.shoreHardness': 'Shore hardness:',
    'addfilament.specs.impactStrength': 'Charpy impact strength (J/cm²):',
    'addfilament.specs.youngsModulus': 'Young\'s modulus (MPa):',
    'addfilament.specs.retraction': 'Retraction (mm):',
    'addfilament.specs.nozzleDiameterMin': 'Min. nozzle diameter (mm):',
    'addfilament.specs.printSpeedMin': 'Print speed min (mm/s):',
    'addfilament.specs.printSpeedMax': 'Print speed max (mm/s):',

    // Edit filament modal
    'editfilament.title': 'Edit filament:',
    'editfilament.alert.noColor': 'Filament must have at least one color!',
    'editfilament.submit': 'Save changes',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('pl');

  // Optional: remember language in localStorage
  useEffect(() => {
    const stored = window.localStorage.getItem('app_lang');
    if (stored === 'pl' || stored === 'en') {
      setLang(stored);
    }
  }, []);

  useEffect(() => {
    window.localStorage.setItem('app_lang', lang);
  }, [lang]);

  const t = (key) => {
    const dict = translations[lang] || translations.pl;
    return dict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);


